spring.application.name=Application

spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always

gemini.api-key=${GEMINI_API_KEY}
gemini.url=${GEMINI_URL}



 
#spring.security.user.name=admin
#spring.security.user.password=admin